name: Stress test

on:
  workflow_dispatch:

jobs:
  stress:
    runs-on: self-hosted

    steps:
      - name: CPU / IO
        run: |
          echo "Starting stress"
          for i in {1..5}; do
            echo "Loop $i"
            dd if=/dev/zero of=testfile bs=1M count=50
            rm testfile
          done
